version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'tanstack_learn'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tanstack_network

volumes:
  postgres_data:

networks:
  tanstack_network:
